# Generated by Django 3.2.5 on 2021-07-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='uploader',
            field=models.CharField(default='Unkown', max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
