# Generated by Django 3.2.5 on 2021-07-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210722_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='uploader',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
