# Generated by Django 3.2.5 on 2021-07-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pdf_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
