# Generated by Django 3.2.5 on 2021-07-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_pdf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='name',
        ),
    ]
