# Generated by Django 3.2.5 on 2021-07-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_pdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='name',
            field=models.CharField(default='No name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
